name: Java CI

on:
  push:
    branches:
      - "**"
      - "!master"
      - "!develop"
  pull_request:
    types:
      - closed
    branches:
      - "master"
      - "develop"
    paths:
      - "**/src/main/**"
      - "**pom.xml"
      - "Dockerfile"
      - ".github/workflows/deploy.yml"

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
        matrix: ${{ steps.setmatrix.outputs.matrix }}

    steps:

      - name: Set Dynamic Env Matrix
        id: setmatrix
        run: |
          if [ ${{ github.event.pull_request.base.ref == 'master' }} == true ]; then 
            matrixStringifiedObject="{\"include\":[{\"environment\":\"uat\", \"env_short\": \"u\"},{\"environment\":\"prod\", \"env_short\": \"p\"}]}"
          elif [ ${{ github.event.pull_request.base.ref == 'develop' }} == true ]; then
            matrixStringifiedObject="{\"include\":[{\"environment\":\"dev\", \"env_short\": \"d\"}]}"        
          else
            matrixStringifiedObject=""
          fi
          echo "matrix=$matrixStringifiedObject" >> $GITHUB_OUTPUT          
      
  deploy:
    name: "Deploy on ECS"
    if: ${{ needs.build.outputs.matrix != '' }}
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    strategy:
        matrix: ${{ fromJson(needs.build.outputs.matrix) }}
         
    continue-on-error: false
    environment: ${{ matrix.environment }}
    env:
      AWS_REGION: eu-south-1

    steps:
      - name: Release
        if: ${{ matrix.environment == 'prod' }}
        id: release
        # from https://github.com/cycjimmy/semantic-release-action/commits/main
        uses: cycjimmy/semantic-release-action@bdd914ff2423e2792c73475f11e8da603182f32d
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}